### PR TITLE
Feature/accesslint - DMR-95

### PR DESCRIPTION
**Pull request by VivianChu**

### CODE REVIEW

**Comment by VivianChu** [comment]
Found 7 new accessibility issues: 
```
'http://localhost:3000/ | serious | <html> element must have a valid lang attribute | ["html"]'
'http://localhost:3000/ | serious | <html> element must have a valid lang attribute | ["html"]'
'http://localhost:3000/ | critical | Form elements must have labels | ["#search"]'
'http://localhost:3000/ | critical | Radio inputs with the same name attribute value must be part of a group | ["#home-container > .content > form > .search > div > label:nth-of-type(1) > input"]'
'http://localhost:3000/ | serious | <html> element must have a valid lang attribute | ["html"]'
'http://localhost:3000/ | critical | Form elements must have labels | ["#search"]'
'http://localhost:3000/ | critical | Radio inputs with the same name attribute value must be part of a group | ["#home-container > .content > form > .search > div > label:nth-of-type(1) > input"]'
```

**Comment by mcritchlow** [comment]
@VivianChu that's looking promising!

**Comment by VivianChu** [comment]
Found 7 new accessibility issues: 
```
'http://localhost:3000/ | serious | <html> element must have a valid lang attribute | ["html"]'
'http://localhost:3000/ | serious | <html> element must have a valid lang attribute | ["html"]'
'http://localhost:3000/ | critical | Form elements must have labels | ["#search"]'
'http://localhost:3000/ | critical | Radio inputs with the same name attribute value must be part of a group | ["#home-container > .content > form > .search > div > label:nth-of-type(1) > input"]'
'http://localhost:3000/ | serious | <html> element must have a valid lang attribute | ["html"]'
'http://localhost:3000/ | critical | Form elements must have labels | ["#search"]'
'http://localhost:3000/ | critical | Radio inputs with the same name attribute value must be part of a group | ["#home-container > .content > form > .search > div > label:nth-of-type(1) > input"]'
```

**Comment by VivianChu** [comment]
@mcritchlow I think I got it working as expected.  I will close this PR to test it more and will open another PR for this feature.

**Pull request closed without merging**
